# Generated by Django 5.1.1 on 2024-11-29 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
