# Generated by Django 5.1.1 on 2024-11-30 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_remove_thread_upvotes_thread_enable_voting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
