# Generated by Django 5.1.1 on 2024-12-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_thread_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created_at',)},
        ),
    ]
