# Generated by Django 5.1.1 on 2024-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_father_name_parent_emergency_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_class',
            new_name='teacher_class',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_id',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_image',
            new_name='teacher_image',
        ),
    ]
