# Generated by Django 5.1.1 on 2024-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_parent_father_email_alter_parent_mother_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_email',
            field=models.EmailField(max_length=100),
        ),
    ]
