# Generated by Django 5.1.1 on 2024-11-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_parent_father_email_alter_parent_mother_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
