# Generated by Django 5.1.1 on 2024-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_parent_father_email_alter_parent_mother_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='father_email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_email',
        ),
    ]
