# Generated by Django 5.1.1 on 2024-11-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
