# Generated by Django 5.1.1 on 2024-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='student_course',
        ),
    ]
