# Generated by Django 5.1.1 on 2024-12-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_participants_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
