# Generated by Django 5.1.1 on 2024-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('academics', 'Academics'), ('events', 'Events'), ('alerts', 'Alerts')], default='academics', max_length=20),
        ),
    ]
