# Generated by Django 5.1.1 on 2024-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_notification_users_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='group_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('everyone', 'Everyone')], default='everyone', max_length=20),
        ),
    ]
