# Generated by Django 5.1.1 on 2024-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_notification_group_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='No title', max_length=100),
            preserve_default=False,
        ),
    ]
