# Generated by Django 5.1.1 on 2024-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
