# Generated by Django 5.1.1 on 2024-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_notification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
