# Generated by Django 5.1.1 on 2024-11-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_notification_downvotes_notification_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='voters',
        ),
        migrations.CreateModel(
            name='VotingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_options', to='school.notification')),
            ],
        ),
    ]
