# Generated by Django 5.1.1 on 2024-11-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_votingoption_votes_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='votingoption',
            name='votes',
        ),
    ]
