# Generated by Django 5.1.1 on 2024-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_remove_votingoption_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
