# Generated by Django 5.1.1 on 2024-12-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_notification_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_date',
        ),
    ]
